Lecture des acquittements
gbip/drs_0x01_driver pull request #1
Opened 2018-10-12 11:48 UTC by goowza

Ploups voila mon code amélioré pour récupérer les données que le servo envoie quand on fait un read (EEP ou RAM). Il marche (pour 2 tests en tout cas :D) mais il est pas super élégant ;-;
Bonne lecture, a+ dans le bus :)

2018-10-12 12:19 UTC, gbip requested changes

2018-10-12 12:19 UTC, gbip commented on src/reader.rs
> +pub enum ACKcmd {
Comme c'est la partie de la librairie qui est publique, ça serait bien de rendre ces types plus "rustic".
Entre autre : utiliser `addr::WritableEEPAddr` pour `EEPRead`, de même pour RAM read.
En gros : les messages qui contiennent des données les contiennent dans les types.
Je sais pas si c'est très clair.

Exemple :

```rust
pub enum ACKcmd {
    EEPRead(WritableEEPAddr),
    RAMRead(WritableRAMAddr),
    Rollback,
    // etc.
}

```

Pour t'aider dans la déserialisation, tu peut utiliser une struc que tu remplis petit à petit dans la machine à état, et à la fin tu la convertie en  `ACKcmd` :wink:

2018-10-12 12:19 UTC, gbip commented on src/reader.rs
> +}
Pour la struct d'aide que tu remplis au fur et à mesure de l'avancée dans la machine à état, on peut voir la chose de deux façons : 

* soit une struct rempli d'options auxquels tu assignes petit à petit des valeurs, par contre tu as plein d'unwrap à un moment
* Soit tu utilises le système de type à ton avantage en faisant une chaîne de struct. 
```
+---------+          +----------+         +---------------+      +--------------------+
|EEPRead1 +--------> |EEPRead2  +-------> |EEPRead3       +----> |EEPreadDone         |
+-> len   |          +-> len    |         +-> len         |      +-> lean             |
+---------+          |-> addr   |         |-> addr        |      |-> addr             |
                     +----------+         |-> data1       |      |-> data1            |
                                          +---------------+      |-> data2            |
                                                                 +--------------------+
```
Cette chaîne de struct peut aussi prendre la forme d'une `enum` (je te recommande cette version !)
```
+-------------------------------------+
|   Enum EEPReadParser                |
|                                     |
|       +-----------------+           |
|       |WaitingForLen    +--------+  |
|       +-----------------+        |  |
|                                  |  |
|       +-----------------+ <------+  |
|       |WaitingForAddr   |           |
|       +-> len           |           |
|       +-----------------+--------+  |
|                                  |  |
|       +-----------------+ <------+  |
|       |WaitingForData1  |           |
|       +-> lend          |           |
|       |-> addr          |           |
|       +-----------------+--------+  |
|                                  |  |
|       +-----------------+ <------+  |
|       |WaitingForData2  |           |
|       +-> lend          |           |
|       |-> addr          |           |
|       |-> data1         |           |
|       +-----------------+           |
|                                     |
|                                     |
+-------------------------------------+

```

Du côté de ta machine à état tu pourrait faire des petites machines à état pour chaque type de message avec des données (EEPRead, RAMRead, etc.) et une grosse machine à état pour les liées.
Tu aurais alors 4 structure de données : 
* la machine à état qui lis :
    * packet size
    * packet id
    * checksum1 & checksum 2
    * cmd
* la machine qui lis les informations en lien avec la commande (si c'est un read, l'adresse, la longueur et les données, etc.)
* la struct qui contiens toutes les machines à état pour faire le lien entre elle et un buffer pour stocker les trames

A savoir que les machines à états pour les commandes peuvent renvoyer `Result<(),()>` comme ça tu sais si ça se passe bien !

Après c'est peut être un peu compliqué à implémenter, tiens moi au courant.

Ah oui, et un conseil : prends le temps de bien nommer tes types ! :smile:

2018-10-12 14:54 UTC, goowza commented on src/reader.rs
> +pub enum ACKcmd {
Je suis pas sur de bien comprendre, il faudrait que les commandes de type "read" contiennent l'adresse à laquelle on est allé lire dans la mémoire ? 
Et ça serait pas plutôt des "Readable" plutôt que des "Writable" du coup ?

2018-10-12 15:13 UTC, gbip commented on src/reader.rs
> +pub enum ACKcmd {
Non, en gros la variante de l'enum représente l'adresse, et les données sont contenues dans la variante !
Et le Writable : il faudra renommer, mais en attendant bah oui c'est pas un super nom...

2018-10-12 15:45 UTC, goowza commented on src/reader.rs
> +pub enum ACKcmd {
Mais je croyais que les variantes de ACKcmd (genre EEPRead ou RAMRead) ça représentait des types de commande *-* Mais je crois que je commence à comprendre l'idée plus ou moins :|

Par exemple dans un ACKcmd de type EEPRead tu as l'adresse à laquelle tu es allé lire et dans cette adresse il y a les données lues sur 1 ou 2 octets ? 

Désolé j'ai du mal et c'est la fin de journée x__x

2018-10-12 19:47 UTC, gbip commented on src/reader.rs
> +pub enum ACKcmd {
Pas de soucis tu as parfaitement compris !
Voici un exemple :smile: :
```rust
enum ACKcmd {
// ...
EEPRead(WritableEEPAddr),
// ...
}
```

2018-10-14 14:54 UTC, gbip requested changes
Ah oui effectivement TryFrom est pas encore stable (ça arrive d'ici décembre).
La solution en attendant c'est d'utiliser une [librairie](https://crates.io/crates/try_from) qui fait exactement la même chose :smile:
Bon courage et sorry pour la mauvaise piste...

2018-10-14 16:18 UTC, gbip requested changes

2018-10-14 16:18 UTC, gbip commented on src/addr.rs
> +impl TryFrom<u8> for ReadableRamAddr {
Là je vois deux choses qui manquent :
* le `extern crate try_from;`
* le `use try_from::TryFrom;`

:wink:

2018-10-26 06:50 UTC, gbip commented on src/reader.rs
> +        use addr::ReadableEEPAddr;
Penses à bien la testé ta fonction :wink:

2018-10-28 16:57 UTC, gbip commented
Du coup, est-ce que je peut merger ou il te reste encore des trucs à tester ?

2018-10-29 12:03 UTC, merged